import type { Metadata } from "next";
import "@aws-amplify/ui-react/styles.css";
import "./globals.css";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigureAmplifyClientSide>{children}</ConfigureAmplifyClientSide>
      </body>
    </html>
  );
}
